name: Deploy PUSH

on:
  push:
    branches: [ foobar ]
    
jobs:
  check:
    outputs:
      last: github.event.after == steps.last_commit.outputs.sha
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Wait 10 seconds
        run: |
          sleep 10
          
      - uses: octokit/request-action@v2.x
        id: fetch
        with:
          route: GET /repos/${{ github.repository }}/branches/${{ github.event.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: last commit
        id: last_commit
        run: |
          echo ${{ github.event.after }}
          echo ${{ fromJSON(steps.fetch.outputs.data).commit.sha }}
          echo "::set-output name=sha::${{ fromJSON(steps.fetch.outputs.data).commit.sha }}"
  work:
    runs-on: ubuntu-latest
    needs: [check]
    if: needs.check.outputs.last == 'true'
    steps:
      - run: |
          echo "Do it !"
