# This is a basic workflow to help you get started with Actions

name: Deploy PUSH

# Controls when the action will run. 
on:
  push:
    branches: [ foobar ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    outputs:
      last: ${{ github.event.after == steps.last_commit.outputs.sha }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Wait 10 seconds
        run: |
          sleep 30
          
      - uses: octokit/request-action@v2.x
        id: fetch
        with:
          route: GET /repos/${{ github.repository }}/branches/${{ github.event.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: last commit
        id: last_commit
        run: |
          echo "::set-output name=sha::${{ fromJSON(steps.fetch.outputs.data).commit.sha }}"
  work:
    runs-on: ubuntu-latest
    needs: [check]
    if: needs.check.outputs.last
    steps:
      - run: |
          echo "Do it !"
